---
services:
  box:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: box
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/
      - TITLE=TheBox
      - DISABLE_IPV6=1
    volumes:
      - thbox:/config
    devices:
      - /dev/dri:/dev/dri
    shm_size: "1gb"
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - vpn

  vpn:
    image: alpine:latest
    command: sh -c 'apk add --no-cache openvpn; openvpn --config /config.ovpn'
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - "${PWD}/${REMOTE_CONFIG}:/config.ovpn:ro"
    networks:
      - vpn_network
    ports:
      - 3000:3000
      - 3001:3001

networks:
  vpn_network:
    driver: bridge

volumes:
  thbox: {}

